name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '0'
        severity: 'HIGH,CRITICAL'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Load Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: prodigywebapp:latest
        outputs: type=docker,dest=/tmp/image.tar

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'prodigywebapp:latest'
        format: 'table'
        exit-code: '0'
        severity: 'HIGH,CRITICAL'
